# ===================================================================
# Local CI specific properties: this file will only be loaded during startup if the profile localci is active
#
# This configuration overrides the application.yml file.
# ===================================================================
artemis:
    continuous-integration:
        # The Docker connection URI to be used by docker-java to connect to the system's Docker installation. Use "unix:///var/run/docker.sock" for Unix based systems and "tcp://localhost:2375" for Windows systems.
        docker-connection-uri: unix:///var/run/docker.sock
        # Set this to true if you want to specify the number of build that can run concurrently on this node. If false, the number will be determined based on system resources.
        specify-concurrent-builds: false
        # The number of builds that can run concurrently on this node.
        concurrent-build-size: 1
        # If true, the CI jobs will be executed asynchronously. If false, the CI jobs will be executed synchronously (e.g. for debugging and tests).
        asynchronous: true
        # The maximum number of seconds that a CI job is allowed to run. If the job exceeds this time, it will be terminated.
        # The number of builds that can be in the local CI queue at the same time. Choosing a small value can prevent the CI system from being overloaded on slow machines. Jobs that are submitted when the queue is already full, will be discarded.
        queue-size-limit: 100


